### ISSUE TITLE
Question about training

### ISSUE THREAD

**Issue by Mozolotov809** [Thijsvanede/DeepCASE#10]
Hi, reading this paper make me feel astonish and inspired!!!
I would like to implement this algorithm in real environment. I want to train this algorithm into real business, and adjust it to fit in.
But I got a question here, I don't know which method to choose. The first one is that I use a little bit data, such as a week data which include almost all kinds of alarms to train , and then enlarge the amount of data. The other one is that I use one type of alarms to train, and make this fit to real situation, and then add another type of alarm to continue, and so on, until the algorithm absorb all of the alarms.
Would you please give me some advice? Which one is quicker, and which one could be more accurate?

**Comment by Thijsvanede** [comment]
Hi Mozolotov809,

- The training time depends only on the total amount of data that you give to it, so either using the full data once, or parts of the data in little chunks will be equivalent.
- Regarding accuracy, this will depend on the type of data that you train with, but in general, the closer your dataset is to a real-world scenario, the more accurate DeepCASE will become.
