### ISSUE TITLE
Project packaging - where to store metadata?

### ISSUE THREAD

**Issue by noah-de** [Thijsvanede/DeepCASE#3]
After reading the revised instructions on [packaging](https://packaging.python.org/en/latest/tutorials/packaging-projects/), we might want to consider updating our approach for where we store metadata: looks like _pyproject.toml_ might be the new place to put it.

See [PEP 517](https://peps.python.org/pep-0517/) and [PEP 518](https://peps.python.org/pep-0518/) for background and details.

https://peps.python.org/pep-0621/

**Comment by noah-de** [comment]
Not too bad. 
I just updated my sample python module: https://github.com/Feralo/vanilla_pkg
and was able to publish it: https://pypi.org/project/vanilla-pkg/

**Comment by Thijsvanede** [comment]
Awesome, thanks. Yes, I will have a look at it next week, it should not be too much work.

**Comment by noah-de** [comment]
This may be a non issue
