### ISSUE TITLE
Just reporting a trivial bug and its solution. Correct me if im wrong in my understanding please.

### ISSUE THREAD

**Issue by Ammar-Amjad** [Thijsvanede/DeepCASE#6]
**Describe the bug**
I ran the command from DeepCASE documentation:
-> python3 deepcase sequence --txt C:\DeepCASE\data\hdfs_train.txt --save-sequences sequences.save
but it threw error
![Error](https://user-images.githubusercontent.com/39439739/200138374-d8cdd85c-404b-4b9a-97cc-8a56d9fdd766.png)

Then I just corrected the preprocessor's method from .txt to .text in the __main__ python file and it fixed the error.
![Correct](https://user-images.githubusercontent.com/39439739/200138380-51908fb9-ee35-44a9-aafb-725a7950951c.png)

I suppose this is the correct working.

**To Reproduce**
1. Just clone the git repo
2. Follow the commands on the website
3. The command below will throw error:
python3 deepcase sequence --txt <file path>--save-sequences sequences.save

![image](https://user-images.githubusercontent.com/39439739/200138196-15ac2fbc-527c-4d8b-b72f-45f41a278271.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version Python 3.7.9

**Additional context**
Just highlighting as its a trivial error and can be fixed easily.
And if I'm wrong, I would love to be corrected about proper usage of DeepCASE.

**Comment by Thijsvanede** [comment]
Thank you very much for the bug report, you are indeed correct this should be `preprocessor.text()`, I will update this in the repository :+1:
