### ISSUE TITLE
Can you provide the data example.csv file used in the example_module.py file

### ISSUE THREAD

**Issue by kunzeng-ch** [Thijsvanede/DeepCASE#7]
Hello! Can you provide the data example.csv file used in the example_module.py file, I want to run it to see what the result is

**Comment by Thijsvanede** [comment]
Sorry for the late reply. There is no `example.csv` file, it is there as a stub to replace with your own data files. However, to illustrate the format I have transformed the `example/hdfs/hdfs_test_normal` dataset into a `.csv` format and uploaded it to the `example/data/example.csv` directory.

**Comment by Thijsvanede** [comment]
File became too big, I will upload the script to transform txt files into csv files
